import Head from 'next/head';
import Image from 'next/image';
import localFont from 'next/font/local';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { getSortedPostsData } from '@/lib/posts';
import { useEffect, useState } from 'react';

// import fs from 'fs';
// import path from 'path';

// export async function getServerSideProps() {
//   console.log('server side props', (Math.random() * 9999) >> 0);
//   // const filePath = path.join(process.cwd(), 'data', 'example.txt');
//   // const data = fs.readFileSync(filePath, 'utf8');
//   // return { props: { data } };
//   return {
//     props: {
//       count: 10,
//     },
//   };
// }

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export default function Home(props) {
  console.log('props', props);
  // const res = await fetch('https://api.github.com/repos/vercel/next.js');
  // const repo = await res.json();

  // const [info, setInfo] = useState({});
  // useEffect(() => {
  //   console.log('hello');
  //   fetch('https://api.github.com/repos/vercel/next.js')
  //     .then((res) => {
  //       return res.json();
  //     })
  //     .then((repo) => {
  //       console.log(repo);
  //       setInfo(repo);
  //     })
  //     .catch((err) => {
  //       console.log(err);
  //     });
  // }, []);
  return (
    <>
      <Head>
        <title>Create Next App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={180}
            height={38}
            priority
          />
          <ol>
            {/* <li>{info.stargazers_count}</li> */}
            <li>
              Get started by editing <code>pages/index.js</code>.
            </li>
            <li>Save and see your changes instantly.</li>
          </ol>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                className={styles.logo}
                src="https://nextjs.org/icons/vercel.svg"
                alt="Vercel logomark"
                width={20}
                height={20}
              />
              Deploy now
            </a>
            <a
              href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
              className={styles.secondary}
            >
              Read our docs
            </a>
          </div>
        </main>
        <footer className={styles.footer}>
          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="https://nextjs.org/icons/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            Learn
          </a>
          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="https://nextjs.org/icons/window.svg"
              alt="Window icon"
              width={16}
              height={16}
            />
            Examples
          </a>
          <a
            href="https://nextjs.org?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            <Image
              aria-hidden
              src="https://nextjs.org/icons/globe.svg"
              alt="Globe icon"
              width={16}
              height={16}
            />
            Go to nextjs.org →
          </a>

          <Link href="/post/first-post">
            <style jsx>
              {`
                span {
                  color: red;
                }
              `}
            </style>
            <Image
              aria-hidden
              src="https://nextjs.org/icons/file.svg"
              alt="File icon"
              width={16}
              height={16}
            />
            <span>First Post</span>
          </Link>
        </footer>
      </div>
    </>
  );
}

// 在构建时与渲染页面，并获取数据
export async function getStaticProps() {
  const random = (Math.random() * 999) >> 0;
  console.log('static props', random);
  const fs = require('fs');
  const path = require('path');
  const data = fs.readFileSync(
    path.join(process.cwd(), 'posts', 'pre-rendering.md')
  );
  console.log(data);
  return {
    props: {
      count: random,
    },
  };
}
